import { Quantity } from './Quantity';
import { ItemIdentification } from './ItemIdentification';
import { DocumentReference } from './DocumentReference';
import { Country } from './Country';
import { CommodityClassification } from './CommodityClassification';
import { TransactionConditions } from './TransactionConditions';
import { HazardousItem } from './HazardousItem';
import { TaxCategory } from './TaxCategory';
import { ItemProperty } from './ItemProperty';
import { Party } from './Party';
import { Address } from './Address';
import { ItemInstance } from './ItemInstance';

export class Item {
    description: Array<String>;
    packQuantity: Quantity;
    packSizeNumeric: number;
    catalogueIndicator: boolean;
    name: String;
    hazardousRiskIndicator: boolean;
    additionalInformation: String;
    keyword: Array<String>;
    brandName: Array<String>;
    representationName: Array<String>;
    buyersItemIdentification: ItemIdentification;
    sellersItemIdentification: ItemIdentification;
    manufacturersItemIdentification: Array<ItemIdentification>;
    standardItemIdentification: ItemIdentification;
    catalogueItemIdentification: ItemIdentification;
    additionalItemIdentification: Array<ItemIdentification>;
    catalogueDocumentReference: DocumentReference;
    itemSpecificationDocumentReference: Array<DocumentReference>;
    originCountry: Country;
    commodityClassification: Array<CommodityClassification>;
    transactionConditions: Array<TransactionConditions>;
    hazardousItem: Array<HazardousItem>;
    classifiedTaxCategory: Array<TaxCategory>;
    additionalItemProperty: Array<ItemProperty>;
    manufacturerParty: Array<Party>;
    informationContentProviderParty: Party;
    originAddress: Array<Address>;
    itemInstance: Array<ItemInstance>;
    id: String;
}