#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker tag openfact/openfact-ui openfact/openfact-ui:$(git rev-parse --short HEAD);
docker tag openfact/openfact-ui-openshift openfact/openfact-ui-openshift:$(git rev-parse --short HEAD);
docker push openfact/openfact-ui
docker push openfact/openfact-ui-openshift
