import { UBLExtensions } from './common/UBLExtensions';
import { Period } from './common/Period';
import { Response } from './common/Response';
import { OrderReference } from './common/OrderReference';
import { BillingReference } from './common/BillingReference';
import { DocumentReference } from './common/DocumentReference';
import { Signature } from './common/Signature';
import { SupplierParty } from './common/SupplierParty';
import { CustomerParty } from './common/CustomerParty';
import { Party } from './common/Party';
import { ExchangeRate } from './common/ExchangeRate';
import { AllowanceCharge } from './common/AllowanceCharge';
import { TaxTotal } from './common/TaxTotal';
import { MonetaryTotal } from './common/MonetaryTotal';
import { CreditNoteLine } from './common/CreditNoteLine';

import { Model } from '../model';

export class CreditNote extends Model {
    ublExtensions: UBLExtensions;
    ublVersionID: String;
    customizationID: String;
    profileID: String;
    idUbl: String;
    copyIndicator: boolean;
    uuid: String;
    issueDate: Date;
    issueTime: Date;
    taxPointDate: Date;
    note: Array<String>;
    documentCurrencyCode: String;
    taxCurrencyCode: String;
    pricingCurrencyCode: String;
    paymentCurrencyCode: String;
    paymentAlternativeCurrencyCode: String;
    accountingCostCode: String;
    accountingCost: String;
    lineCountNumeric: number;
    invoicePeriod: Array<Period>;
    discrepancyResponse: Array<Response>;
    orderReference: OrderReference;
    billingReference: Array<BillingReference>;
    despatchDocumentReference: Array<DocumentReference>;
    receiptDocumentReference: Array<DocumentReference>;
    contractDocumentReference: Array<DocumentReference>;
    additionalDocumentReference: Array<DocumentReference>;
    signature: Array<Signature>;
    accountingSupplierParty: Array<SupplierParty>;
    accountingCustomerParty: Array<CustomerParty>;
    payeeParty: Array<Party>;
    taxRepresentativeParty: Array<Party>;
    taxExchangeRate: Array<ExchangeRate>;
    pricingExchangeRate: Array<ExchangeRate>;
    paymentExchangeRate: Array<ExchangeRate>;
    paymentAlternativeExchangeRate: Array<ExchangeRate>;
    allowanceCharge: Array<AllowanceCharge>;
    taxTotal: Array<TaxTotal>;
    legalMonetaryTotal: Array<MonetaryTotal>;
    creditNoteLine: Array<CreditNoteLine>;
    id: String;
}