import { UBLExtensions } from './common/UBLExtensions';
import { Period } from './common/Period';
import { Response } from './common/Response';
import { OrderReference } from './common/OrderReference';
import { BillingReference } from './common/BillingReference';
import { DocumentReference } from './common/DocumentReference';
import { Signature } from './common/Signature';
import { SupplierParty } from './common/SupplierParty';
import { CustomerParty } from './common/CustomerParty';
import { Party } from './common/Party';
import { Payment } from './common/Payment';
import { ExchangeRate } from './common/ExchangeRate';
import { AllowanceCharge } from './common/AllowanceCharge';
import { TaxTotal } from './common/TaxTotal';
import { MonetaryTotal } from './common/MonetaryTotal';
import { DebitNoteLine } from './common/DebitNoteLine';

export class DebitNote {
    ublExtensions: UBLExtensions;
    ublVersionID: String;
    customizationID: String;
    profileID: String;
    idUbl: String;
    copyIndicator: boolean;
    uuid: String;
    issueDate: Date;
    issueTime: Date;
    note: Array<String>;
    taxPointDate: Date;
    documentCurrencyCode: String;
    taxCurrencyCode: String;
    pricingCurrencyCode: String;
    paymentCurrencyCode: String;
    paymentAlternativeCurrencyCode: String;
    accountingCostCode: String;
    accountingCost: String;
    lineCountNumeric: number;
    invoicePeriod: Array<Period>;
    discrepancyResponse: Array<Response>;
    orderReference: OrderReference;
    billingReference: Array<BillingReference>;
    despatchDocumentReference: Array<DocumentReference>;
    receiptDocumentReference: Array<DocumentReference>;
    contractDocumentReference: Array<DocumentReference>;
    additionalDocumentReference: Array<DocumentReference>;
    signature: Array<Signature>;
    accountingSupplierParty: SupplierParty;
    accountingCustomerParty: CustomerParty;
    payeeParty: Party;
    taxRepresentativeParty: Party;
    prepaidPayment: Array<Payment>;
    taxExchangeRate: ExchangeRate;
    pricingExchangeRate: ExchangeRate;
    paymentExchangeRate: ExchangeRate;
    paymentAlternativeExchangeRate: ExchangeRate;
    taxTotal: Array<TaxTotal>;
    requestedMonetaryTotal: MonetaryTotal;
    debitNoteLine: Array<DebitNoteLine>;
    id: String;
}